name: Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0/30 15-22 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^2'
      - run: |
          go install github.com/muesli/markscribe@master
          markscribe ./templates/readme.md.tpl > README.md
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LITERAL_EMAIL: ${{ secrets.LITERAL_EMAIL }}
          LITERAL_PASSWORD: ${{ secrets.LITERAL_PASSWORD }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'docs: Update generated README'
          branch: dev
          commit_user_name: readme-scribe robot
          commit_user_email: actions@github.com
          commit_author: readme-scribe robot <actions@github.com>
